medical_warehouse:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: postgres
      port: 5432
      dbname: medical_warehouse
      schema: public
      threads: 4
      keepalives_idle: 0